# configuration/base.yaml
application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://127.0.0.1"
  sender_email: "johannes.jyrgenson@gmail.com"
  # New value
  # We are only setting the dev value
  # We will deal with the production token outside of version control
  authorization_token: "my-secret-token"
